/*
 * imgeditor common include file
 * qianfan Zhao
 */
#ifndef IMAGE_EDITOR_H
#define IMAGE_EDITOR_H

#include <stdio.h>
#include <stdint.h>
#include <endian.h>
#include <unistd.h>
#include <linux/types.h> /* import __le16, __le32... */
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include "list_head.h"
#include "json_helper.h"

int get_verbose_level(void);

#define SIZE_KB(x)				((x) << 10)
#define SIZE_MB(x)				((x) << 20)
#define SIZE_GB(x)				((x) << 30)
#define SIZEMASK_KB				(SIZE_KB(1) - 1)
#define SIZEMASK_MB				(SIZE_MB(1) - 1)
#define SIZEMASK_GB				(SIZE_GB(1) - 1)

const char *smart_format_size(uint64_t sz, char *buf, size_t bufsz);

#define le16_to_cpu(x)				le16toh(x)
#define be16_to_cpu(x)				be16toh(x)
#define le32_to_cpu(x)				le32toh(x)
#define be32_to_cpu(x)				be32toh(x)
#define le64_to_cpu(x)				le64toh(x)
#define be64_to_cpu(x)				be64toh(x)
#define cpu_to_le16(x)				htole16(x)
#define cpu_to_le32(x)				htole32(x)
#define cpu_to_le64(x)				htole64(x)
#define cpu_to_be16(x)				htobe16(x)
#define cpu_to_be32(x)				htobe32(x)
#define cpu_to_be64(x)				htobe64(x)

#define fprintf_if_force_type(fmt, ...) 	do {	\
	if (force_type) {				\
		fprintf(stderr, fmt, ##__VA_ARGS__);	\
	}						\
} while (0)

int fileopen(const char *file, int flags, mode_t mode);
int64_t filelength(int fd);

void hexdump(const void *buf, size_t bufsz, unsigned long baseaddr);

/* SINGLE_BIN: the firmware is generated by padding other control bytes.
 * MULTI_BIN:  the firmware is merged by multi binary files.
 */
#define IMGEDITOR_FLAG_SINGLE_BIN			(0 << 0)
#define IMGEDITOR_FLAG_CONTAIN_MULTI_BIN		(1 << 0)

#define IMGEDITOR_FLAG_HIDE_INFO_WHEN_LIST		(1 << 1)

struct imgeditor {
	const char		*name;
	const char		*descriptor;
	unsigned int		flags;
	size_t			header_size;
	size_t			private_data_size;
	void			*private_data;
	struct list_head	head;

	/* p: point to private_data alloced by the core level. */
	int			(*init)(void *p);
	int			(*detect)(void *p, int force_type, int fd);
	int			(*list)(void *p, int fd, int argc, char **argv);
	int			(*pack)(void *p, const char *dir, int fd_outimg, int argc, char **argv);
	int			(*unpack)(void *p, int fd, const char *outdir, int argc, char **argv);
	void			(*exit)(void *p);
};

void register_imgeditor(struct imgeditor *editor);

#define REGISTER_IMGEDITOR(e)						\
static void __attribute__((constructor)) register_imgeditor_##e(void)	\
{									\
	register_imgeditor(&e);						\
}

#define aligned_length(len, align)	(((len) + (align) - 1) / (align) * (align))

struct length64 {
	uint32_t			lo;
	uint32_t			hi;
};

struct length64_hilo {
	uint32_t			hi;
	uint32_t			lo;
};

#define to_length64(len) 					\
	(((uint64_t)((len)->hi) << 32) | ((len)->lo))

#define set_length64(l64, l)		do {			\
	(l64)->hi = (l >> 32) & 0xffffffff;			\
	(l64)->lo = (l >>  0) & 0xffffffff;			\
} while (0)

#define prints(item, header)	do {				\
	printf("%20s:\t%.*s\n", #item, 				\
		(int)sizeof((header)->item), (header)->item);	\
} while (0)

#define printu32(item, header)	do {				\
	printf("%20s:\t%d\n", #item, (header)->item);		\
} while (0)

#define printx32(item, header) do {				\
	printf("%20s:\t0x%08x\n", #item, (header)->item);	\
} while (0)

#define printlen64(item, header) do {				\
	uint64_t l = to_length64(&((header)->item));		\
	printf("%20s:\t%" PRIu64 "\n", #item, l);		\
} while (0)

#define jsonputs(root, item, header) do {			\
	char s[256];						\
	snprintf(s, sizeof(s), "%.*s", 				\
		 (int)sizeof((header)->item), (header)->item);	\
	json_create_or_update_string_value(root, #item, s);	\
} while (0)

#define jsonputu32(root, item, header) do {			\
	char s[64];						\
	snprintf(s, sizeof(s), "%d", (header)->item);		\
	json_create_or_update_string_value(root, #item, s);	\
} while (0)

#define jsonputx32(root, item, header) do {			\
	char s[64];						\
	snprintf(s, sizeof(s), "0x%x", (header)->item);		\
	json_create_or_update_string_value(root, #item, s);	\
} while (0)

#define jsonloads(root, item, header) do {				\
	const char *s;							\
	s = json_get_string_value_bypath(root, #item);			\
	memset((header)->item, 0, sizeof((header)->item));		\
	if (s)								\
		strncpy((header)->item, s, sizeof((header)->item) - 1);	\
} while (0)

#define jsonputx64(root, item, header) do {			\
	char s[64];						\
	uint64_t l = to_length64(&(header)->item);		\
	snprintf(s, sizeof(s), "0x%lx", l); 			\
	json_create_or_update_string_value(root, #item, s);	\
} while (0)

#define jsonloadx32_def(root, item, header, def) do {		\
	uint32_t v = def;					\
	v = json_string_value_to_number_or_default(root, 	\
						#item, 16, v);	\
	(header)->item = v;					\
} while (0)

/* set value to 0xffffffff is not found */
#define jsonloadx32(root, item, header)				\
	jsonloadx32_def(root, item, header, 0xffffffff)

size_t dd(int fdsrc, int fddst, off_t offt_src, off_t offt_dst, size_t sz,
	  void (*bufscan)(uint8_t *buf, size_t sz_buster, void *p),
	  void *private_data);

void hexdump(const void *buf, size_t sz, unsigned long baseaddr);
int xstring(const char *str, const char **endp, uint8_t *buf, size_t len);

void rc4_encode(unsigned char *buf, int len, unsigned char key[16]);
uint32_t crc32 (uint32_t crc, const uint8_t *p, size_t len);

#endif
